# Generated by Django 3.2.13 on 2024-11-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_auto_20241124_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
